package com.example.model;

import java.util.Date;

public class Demo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.d_id
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(主键) */
    private Long dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(名字) */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.create_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(创建时间) */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.update_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(更新时间) */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.delete_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(删除时间) */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.is_enable
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(是否启用) */
    private Byte isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.is_delete
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    /* @Comment(是否删除) */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.d_id
     *
     * @return the value of demo.d_id
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.d_id
     *
     * @param dId the value for demo.d_id
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.create_time
     *
     * @return the value of demo.create_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.create_time
     *
     * @param createTime the value for demo.create_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.update_time
     *
     * @return the value of demo.update_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.update_time
     *
     * @param updateTime the value for demo.update_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.delete_time
     *
     * @return the value of demo.delete_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.delete_time
     *
     * @param deleteTime the value for demo.delete_time
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.is_enable
     *
     * @return the value of demo.is_enable
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.is_enable
     *
     * @param isEnable the value for demo.is_enable
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.is_delete
     *
     * @return the value of demo.is_delete
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.is_delete
     *
     * @param isDelete the value for demo.is_delete
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}