package com.example.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_id
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment() */
    private Long mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.nickname
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment(昵称) */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment(内容) */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.praise_num
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment(点赞数量) */
    private Integer praiseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment() */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_enable
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment() */
    private Byte isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_delete
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    /* @Comment() */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_id
     *
     * @return the value of message.m_id
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public Long getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_id
     *
     * @param mId the value for message.m_id
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setmId(Long mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.nickname
     *
     * @return the value of message.nickname
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.nickname
     *
     * @param nickname the value for message.nickname
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.praise_num
     *
     * @return the value of message.praise_num
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public Integer getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.praise_num
     *
     * @param praiseNum the value for message.praise_num
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setPraiseNum(Integer praiseNum) {
        this.praiseNum = praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_enable
     *
     * @return the value of message.is_enable
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_enable
     *
     * @param isEnable the value for message.is_enable
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_delete
     *
     * @return the value of message.is_delete
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_delete
     *
     * @param isDelete the value for message.is_delete
     *
     * @mbggenerated Mon Apr 24 18:11:43 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}