---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.19:3306/demo?useUnicode=true&amp;characterEncoding=utf-8
    username: ibaixiong
    password: 1234567890
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
    
logging:
  level: 
    org.mybatis: DEBUG
       
mybatis:
  mapper-locations:
  - classpath:com/example/mapping/*.xml
  type-aliases-package: com.example.model

     