logging:
  level: 
    org.mybatis: DEBUG
spring:
  datasource:
    url: jdbc:mysql://192.168.0.247:3306/year?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
mybatis:
  mapper-locations:
  - classpath:com/example/mapping/*.xml
  type-aliases-package: com.example.model

     