package com.example.dao;

import com.example.model.Demo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    Demo selectByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    Demo selectByPrimaryKeyLock(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    List<Demo> selectByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int deleteByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int deleteByPrimaryKeyBulk(@Param("ids") List<Long> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int enableByPrimaryKeyBulk(@Param("ids") List<Long> ids, @Param("enable") Byte enable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int updateByPrimaryKey(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    List<Demo> selectSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Mon Sep 11 11:09:37 CST 2017
     */
    int countSelective(Demo record);
}